services:
  web:
    build:
      context: .
      dockerfile: DockerFile.django
    volumes:
      - ./backend:/app/backend
    ports:
      - "8000:8000"
    env_file:
      - ./backend/.env
    environment:
      - DJANGO_SETTINGS_MODULE=tv_backend.production_settings
  frontend:
    build:
      context: ./frontend
      dockerfile: DockerFile
    volumes:
      - ./frontend:/app
    env_file:
      - ./frontend/.env.docker
    ports:
      - "3000:3000"
    depends_on:
      - web