# Stage 1: Builder
FROM node:20-alpine AS builder

WORKDIR /app

# Copy only the frontend source
COPY ./frontend/package*.json ./
RUN npm install

COPY ./frontend ./
RUN npm run build

# Stage 2: Runtime
FROM node:20-alpine

WORKDIR /app

COPY --from=builder /app/.next ./.next
COPY --from=builder /app/public ./public
COPY --from=builder /app/package*.json ./
COPY --from=builder /app/node_modules ./node_modules
COPY --from=builder /app/next.config.mjs ./

EXPOSE 3000
CMD ["npm", "start"]