# Generated by Django 5.2 on 2025-05-01 09:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market_api', '0002_alter_expertuser_options_alter_expertuser_expert_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='expertuser',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 5, 31, 9, 47, 34, 892531, tzinfo=datetime.timezone.utc)),
        ),
    ]
