# Generated by Django 5.2 on 2025-05-01 11:04

import django.utils.timezone
import market_api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market_api', '0003_expertuser_expires_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='expertuser',
            name='last_paid_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='expertuser',
            name='expires_at',
            field=models.DateTimeField(default=market_api.models.ExpertUser.thirty_days_from_now),
        ),
    ]
