# Generated by Django 5.2.1 on 2025-05-12 19:57

import django.db.models.deletion
import django.utils.timezone
import market_api.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ExpertAdvisor',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('magic_number', models.IntegerField()),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('version', models.CharField(max_length=50)),
                ('author', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('supported_pairs', models.JSONField(blank=True, default=list)),
                ('timeframes', models.JSONField(blank=True, default=list)),
                ('minimum_deposit', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('price', models.DecimalField(decimal_places=2, default=100, max_digits=10)),
                ('instructions', models.URLField(blank=True, max_length=255, null=True)),
                ('image_url', models.URLField(blank=True, max_length=255, null=True)),
                ('file_url', models.URLField(blank=True, max_length=255, null=True)),
                ('parameters', models.JSONField(blank=True, default=dict)),
                ('created_by', models.ForeignKey(default='33a78ee6-12f6-46d5-8b68-6e50563b906c', on_delete=django.db.models.deletion.CASCADE, related_name='expert_advisor_creator', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Expert Advisor',
                'verbose_name_plural': 'Expert Advisors',
                'db_table': 'expert_advisors',
                'ordering': ['-created_at'],
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='ExpertUser',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('subscribed_at', models.DateTimeField(auto_now_add=True)),
                ('last_paid_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('expires_at', models.DateTimeField(default=market_api.models.ExpertUser.thirty_days_from_now)),
                ('expert', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='downloads', to='market_api.expertadvisor')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expert_subscriptions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Expert User',
                'verbose_name_plural': 'Expert Users',
                'db_table': 'expert_users',
                'managed': True,
                'unique_together': {('user', 'expert')},
            },
        ),
    ]
