# Generated by Django 5.2 on 2025-05-01 09:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market_api', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='expertuser',
            options={'managed': True, 'verbose_name': 'Expert User', 'verbose_name_plural': 'Expert Users'},
        ),
        migrations.AlterField(
            model_name='expertuser',
            name='expert',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='downloads', to='market_api.expertadvisor'),
        ),
        migrations.AlterField(
            model_name='expertuser',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expert_subscriptions', to=settings.AUTH_USER_MODEL),
        ),
    ]
