# Generated by Django 5.2.1 on 2025-05-15 09:10

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('market_api', '0002_remove_expertadvisor_file_url_expertadvisor_file'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='expertadvisor',
            unique_together={('magic_number', 'created_by'), ('name', 'created_by')},
        ),
    ]
