# Generated by Django 5.2.1 on 2025-05-26 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market_api', '0003_alter_expertadvisor_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='expertuser',
            name='account_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
