# Generated by Django 5.2 on 2025-05-11 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market_api', '0004_expertuser_last_paid_at_alter_expertuser_expires_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='expertadvisor',
            name='instructions',
            field=models.URLField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='expertadvisor',
            name='minimum_deposit',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='expertadvisor',
            name='price',
            field=models.DecimalField(decimal_places=2, default=100, max_digits=10),
        ),
        migrations.AddField(
            model_name='expertadvisor',
            name='supported_pairs',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='expertadvisor',
            name='timeframes',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
