# Generated by Django 5.2 on 2025-05-11 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market_api', '0005_expertadvisor_instructions_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='expertadvisor',
            name='parameters',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
