# Generated by Django 5.2.1 on 2025-08-07 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market_api', '0005_alter_expertuser_expires_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='expertadvisor',
            name='stripe_price_id',
            field=models.CharField(blank=True, help_text='Stripe price ID for this expert advisor', max_length=255, null=True),
        ),
    ]
