# Generated by Django 5.2.1 on 2025-08-07 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market_api', '0006_expertadvisor_stripe_price_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='expertuser',
            name='stripe_subscription_id',
            field=models.CharField(blank=True, help_text="Stripe subscription ID for this user's subscription to this expert advisor", max_length=255, null=True),
        ),
    ]
