# Generated by Django 5.2.1 on 2025-08-12 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market_api', '0007_expertuser_stripe_subscription_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='expertuser',
            name='state',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
