# Generated by Django 5.2.1 on 2025-05-30 03:03

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('market_api', '0005_alter_expertuser_expires_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Trade',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('open_time', models.DateTimeField()),
                ('close_time', models.DateTimeField(blank=True, null=True)),
                ('profit', models.DecimalField(decimal_places=2, max_digits=12)),
                ('lot_size', models.DecimalField(decimal_places=2, max_digits=10)),
                ('ticker', models.CharField(max_length=10)),
                ('direction', models.CharField(choices=[('BUY', 'Buy'), ('SELL', 'Sell')], max_length=4)),
                ('ticket_number', models.IntegerField()),
                ('expert', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trades', to='market_api.expertadvisor')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trades', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Trade',
                'verbose_name_plural': 'Trades',
                'db_table': 'trades',
                'ordering': ['-open_time'],
                'constraints': [models.UniqueConstraint(fields=('user', 'ticket_number'), name='unique_user_ticket_number')],
            },
        ),
    ]
