# Generated by Django 5.2 on 2025-05-05 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard_api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='trade',
            name='ticker',
            field=models.CharField(default=' ', max_length=10),
            preserve_default=False,
        ),
    ]
