# Generated by Django 5.2 on 2025-05-11 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard_api', '0002_trade_ticker'),
    ]

    operations = [
        migrations.AddField(
            model_name='trade',
            name='direction',
            field=models.CharField(choices=[('BUY', 'Buy'), ('SELL', 'Sell')], default='NONE', max_length=4),
            preserve_default=False,
        ),
    ]
